parameters:
#    orim_google_api.example.class: Orim\GoogleApiBundle\Example

services:
#    orim_google_api.example:
#        class: %orim_google_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
